name: MPMcCormick86
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1122449
title: MPMcCormick86 - Grid Project 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ffff00'
    - '#ff8300'
    - '#808080'
  brandStrength: 0.5
  lightness: 0.4978518
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
