name: MPMcCormick86
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1122449
title: MPMcCormick86 - Grid Project 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ffff00'
    - '#ff8300'
    - '#808080'
  brandStrength: 0.375
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
