name: MPMcCormick86
favicon: null
layout_spectrum: 0.5388167297933251
typography_spectrum: 0.6064618888776749
title: MPMcCormick86 - Grid Project 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ffff00'
    - '#ff8300'
    - '#808080'
  brandStrength: 0.25
  lightness: 0.6821387428790331
  saturation: 0.5426882356405258
  rhythmicContrast: 0.5605021025985479
purpose: []
