name: MPMcCormick86
favicon: null
layout_spectrum: 0.5388167297933251
typography_spectrum: 0.05957
title: MPMcCormick86 - Grid Project 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ffff00'
    - '#ff8300'
    - '#808080'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
