analytics: {}
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ffff00'
    - '#ff8300'
    - '#808080'
  brandStrength: 0.4849624
  lightness: 0.5625
  rhythmicContrast: 0.75
  saturation: 0.5
cta: {}
layout_spectrum: 0.898648
name: MPMcCormick86
opengraph: {}
purpose: []
typography_spectrum: 0.1122449
